{% set name = "llguidance" %}
{% set version = "0.7.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 982451f6b8524a8e45b440be903e6da6b31f03052e86b27775614a388be9d509

build:
  number: 0
  python_version_independent: true
  skip: true  # [is_abi3 and not is_python_min]
  ignore_run_exports:
    from_package:
      - cross-python_${{ target_platform }}  # [build_platform != target_platform]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin >=1.0,<2.0                  # [build_platform != target_platform]
  host:
    - python-abi3  # [is_abi3]
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python

test:
  imports:
    - llguidance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/guidance-ai/llguidance
  summary: Bindings for the Low-level Guidance (llguidance) Rust library for use within Guidance
  license: MIT
  license_file:
    - LICENSE
    - parser/LICENSE
    - toktrie_hf_tokenizers/LICENSE
    - toktrie_hf_downloader/LICENSE
    - toktrie/LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - shermansiu
